//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.12 at 04:50:01 PM PDT 
//


package com.celexus.conniption.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="account" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="accountbalance">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="account" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="accountvalue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="buyingpower">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="cashavailableforwithdrawal" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="daytrading" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="equitypercentage" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="options" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="soddaytrading" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="sodoptions" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="sodstock" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="stock" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="fedcall" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="housecall" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="money">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="accruedinterest" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="cash" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="cashavailable" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="marginbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="mmf" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="total" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="uncleareddeposits" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="unsettledfunds" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="yield" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="securities">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="longoptions" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="longstocks" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="options" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="shortoptions" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="shortstocks" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="stocks" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="total" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="accountholdings">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="holding" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="accounttype" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="costbasis" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="displaydata">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="accounttype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="assetclass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="costbasis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="lastprice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="marketvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="marketvaluechange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="qty" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="gainloss" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="instrument">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="cusip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="factor" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="sectyp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="sym" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="marketvalue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="marketvaluechange" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="purchaseprice" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="qty" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="quote">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                       &lt;element name="lastprice" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="underlying" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="totalsecurities" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "account",
    "accountbalance",
    "accountholdings"
})
public class Accountsummary {

    protected int account;
    @XmlElement(required = true)
    protected Accountbalance accountbalance;
    @XmlElement(required = true)
    protected Accountholdings accountholdings;

    /**
     * Gets the value of the account property.
     * 
     */
    public int getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     */
    public void setAccount(int value) {
        this.account = value;
    }

    /**
     * Gets the value of the accountbalance property.
     * 
     * @return
     *     possible object is
     *     {@link Accountbalance }
     *     
     */
    public Accountbalance getAccountbalance() {
        return accountbalance;
    }

    /**
     * Sets the value of the accountbalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accountbalance }
     *     
     */
    public void setAccountbalance(Accountbalance value) {
        this.accountbalance = value;
    }

    /**
     * Gets the value of the accountholdings property.
     * 
     * @return
     *     possible object is
     *     {@link Accountholdings }
     *     
     */
    public Accountholdings getAccountholdings() {
        return accountholdings;
    }

    /**
     * Sets the value of the accountholdings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accountholdings }
     *     
     */
    public void setAccountholdings(Accountholdings value) {
        this.accountholdings = value;
    }

}
