//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.12 at 04:50:01 PM PDT 
//


package com.celexus.conniption.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="holding" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="accounttype" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="costbasis" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="displaydata">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="accounttype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="assetclass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="costbasis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="lastprice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="marketvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="marketvaluechange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="qty" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="gainloss" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="instrument">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="cusip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="factor" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="sectyp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="sym" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="marketvalue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="marketvaluechange" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="purchaseprice" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="qty" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="quote">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="lastprice" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="underlying" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="totalsecurities" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "holding",
    "totalsecurities"
})
public class Accountholdings {

    protected List<Holding> holding;
    protected float totalsecurities;

    /**
     * Gets the value of the holding property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the holding property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHolding().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Holding }
     * 
     * 
     */
    public List<Holding> getHolding() {
        if (holding == null) {
            holding = new ArrayList<Holding>();
        }
        return this.holding;
    }

    /**
     * Gets the value of the totalsecurities property.
     * 
     */
    public float getTotalsecurities() {
        return totalsecurities;
    }

    /**
     * Sets the value of the totalsecurities property.
     * 
     */
    public void setTotalsecurities(float value) {
        this.totalsecurities = value;
    }

}
