//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.12 at 04:50:01 PM PDT 
//


package com.celexus.conniption.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cashavailableforwithdrawal" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="daytrading" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="equitypercentage" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="options" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="soddaytrading" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="sodoptions" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="sodstock" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="stock" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cashavailableforwithdrawal",
    "daytrading",
    "equitypercentage",
    "options",
    "soddaytrading",
    "sodoptions",
    "sodstock",
    "stock"
})
public class Buyingpower {

    protected float cashavailableforwithdrawal;
    protected float daytrading;
    protected byte equitypercentage;
    protected float options;
    protected float soddaytrading;
    protected float sodoptions;
    protected float sodstock;
    protected float stock;

    /**
     * Gets the value of the cashavailableforwithdrawal property.
     * 
     */
    public float getCashavailableforwithdrawal() {
        return cashavailableforwithdrawal;
    }

    /**
     * Sets the value of the cashavailableforwithdrawal property.
     * 
     */
    public void setCashavailableforwithdrawal(float value) {
        this.cashavailableforwithdrawal = value;
    }

    /**
     * Gets the value of the daytrading property.
     * 
     */
    public float getDaytrading() {
        return daytrading;
    }

    /**
     * Sets the value of the daytrading property.
     * 
     */
    public void setDaytrading(float value) {
        this.daytrading = value;
    }

    /**
     * Gets the value of the equitypercentage property.
     * 
     */
    public byte getEquitypercentage() {
        return equitypercentage;
    }

    /**
     * Sets the value of the equitypercentage property.
     * 
     */
    public void setEquitypercentage(byte value) {
        this.equitypercentage = value;
    }

    /**
     * Gets the value of the options property.
     * 
     */
    public float getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     */
    public void setOptions(float value) {
        this.options = value;
    }

    /**
     * Gets the value of the soddaytrading property.
     * 
     */
    public float getSoddaytrading() {
        return soddaytrading;
    }

    /**
     * Sets the value of the soddaytrading property.
     * 
     */
    public void setSoddaytrading(float value) {
        this.soddaytrading = value;
    }

    /**
     * Gets the value of the sodoptions property.
     * 
     */
    public float getSodoptions() {
        return sodoptions;
    }

    /**
     * Sets the value of the sodoptions property.
     * 
     */
    public void setSodoptions(float value) {
        this.sodoptions = value;
    }

    /**
     * Gets the value of the sodstock property.
     * 
     */
    public float getSodstock() {
        return sodstock;
    }

    /**
     * Sets the value of the sodstock property.
     * 
     */
    public void setSodstock(float value) {
        this.sodstock = value;
    }

    /**
     * Gets the value of the stock property.
     * 
     */
    public float getStock() {
        return stock;
    }

    /**
     * Sets the value of the stock property.
     * 
     */
    public void setStock(float value) {
        this.stock = value;
    }

}
