//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.14 at 02:43:01 PM PDT 
//


package com.celexus.conniption.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accounttype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="assetclass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="costbasis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="marketvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="marketvaluechange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="qty" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="askprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="asksize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bidprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="bidsize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="contracthigh" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="contractlow" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="contractsize" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="delta" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dividendamount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dividendexdate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="dividendpaydate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="dividendyield" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="earningspershare" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="exch" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="expiry" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="gamma" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="high52price" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="highprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="impvolatility" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="lastclosingprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="lastprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="low52price" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="lowprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="nav" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="openinterest" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="openprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="optval" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="optiontype" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="pctchange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="priceearningsratio" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="rho" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="sessionvolume" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="strike" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="theta" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="unknownsymbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vega" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="volatility" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accounttype",
    "assetclass",
    "costbasis",
    "marketvalue",
    "marketvaluechange",
    "qty",
    "askprice",
    "asksize",
    "bidprice",
    "bidsize",
    "change",
    "contracthigh",
    "contractlow",
    "contractsize",
    "delta",
    "desc",
    "dividendamount",
    "dividendexdate",
    "dividendpaydate",
    "dividendyield",
    "earningspershare",
    "exch",
    "expiry",
    "gamma",
    "high52Price",
    "highprice",
    "impvolatility",
    "lastclosingprice",
    "lastprice",
    "low52Price",
    "lowprice",
    "nav",
    "openinterest",
    "openprice",
    "optval",
    "optiontype",
    "pctchange",
    "priceearningsratio",
    "rho",
    "sessionvolume",
    "strike",
    "symbol",
    "theta",
    "unknownsymbol",
    "vega",
    "volatility",
    "volume"
})
public class Displaydata {

    @XmlElement(required = true)
    protected String accounttype;
    @XmlElement(required = true)
    protected String assetclass;
    @XmlElement(required = true)
    protected String costbasis;
    @XmlElement(required = true)
    protected String marketvalue;
    @XmlElement(required = true)
    protected String marketvaluechange;
    protected int qty;
    protected double askprice;
    @XmlElement(required = true)
    protected String asksize;
    protected double bidprice;
    @XmlElement(required = true)
    protected String bidsize;
    protected double change;
    @XmlElement(required = true)
    protected Object contracthigh;
    @XmlElement(required = true)
    protected Object contractlow;
    @XmlElement(required = true)
    protected Object contractsize;
    @XmlElement(required = true)
    protected Object delta;
    @XmlElement(required = true)
    protected String desc;
    protected int dividendamount;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dividendexdate;
    @XmlElement(required = true)
    protected Object dividendpaydate;
    @XmlElement(required = true)
    protected String dividendyield;
    protected double earningspershare;
    @XmlElement(required = true)
    protected String exch;
    @XmlElement(required = true)
    protected Object expiry;
    @XmlElement(required = true)
    protected Object gamma;
    @XmlElement(name = "high52price")
    protected double high52Price;
    protected double highprice;
    @XmlElement(required = true)
    protected Object impvolatility;
    protected double lastclosingprice;
    protected double lastprice;
    @XmlElement(name = "low52price")
    protected double low52Price;
    protected double lowprice;
    @XmlElement(required = true)
    protected Object nav;
    @XmlElement(required = true)
    protected Object openinterest;
    protected double openprice;
    @XmlElement(required = true)
    protected Object optval;
    @XmlElement(required = true)
    protected Object optiontype;
    @XmlElement(required = true)
    protected String pctchange;
    protected int priceearningsratio;
    @XmlElement(required = true)
    protected Object rho;
    @XmlElement(required = true)
    protected String sessionvolume;
    @XmlElement(required = true)
    protected Object strike;
    @XmlElement(required = true)
    protected String symbol;
    @XmlElement(required = true)
    protected Object theta;
    @XmlElement(required = true)
    protected String unknownsymbol;
    @XmlElement(required = true)
    protected Object vega;
    @XmlElement(required = true)
    protected Object volatility;
    @XmlElement(required = true)
    protected String volume;

    /**
     * Gets the value of the accounttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccounttype() {
        return accounttype;
    }

    /**
     * Sets the value of the accounttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccounttype(String value) {
        this.accounttype = value;
    }

    /**
     * Gets the value of the assetclass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetclass() {
        return assetclass;
    }

    /**
     * Sets the value of the assetclass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetclass(String value) {
        this.assetclass = value;
    }

    /**
     * Gets the value of the costbasis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostbasis() {
        return costbasis;
    }

    /**
     * Sets the value of the costbasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostbasis(String value) {
        this.costbasis = value;
    }

    /**
     * Gets the value of the marketvalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketvalue() {
        return marketvalue;
    }

    /**
     * Sets the value of the marketvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketvalue(String value) {
        this.marketvalue = value;
    }

    /**
     * Gets the value of the marketvaluechange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketvaluechange() {
        return marketvaluechange;
    }

    /**
     * Sets the value of the marketvaluechange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketvaluechange(String value) {
        this.marketvaluechange = value;
    }

    /**
     * Gets the value of the qty property.
     * 
     */
    public int getQty() {
        return qty;
    }

    /**
     * Sets the value of the qty property.
     * 
     */
    public void setQty(int value) {
        this.qty = value;
    }

    /**
     * Gets the value of the askprice property.
     * 
     */
    public double getAskprice() {
        return askprice;
    }

    /**
     * Sets the value of the askprice property.
     * 
     */
    public void setAskprice(double value) {
        this.askprice = value;
    }

    /**
     * Gets the value of the asksize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAsksize() {
        return asksize;
    }

    /**
     * Sets the value of the asksize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAsksize(String value) {
        this.asksize = value;
    }

    /**
     * Gets the value of the bidprice property.
     * 
     */
    public double getBidprice() {
        return bidprice;
    }

    /**
     * Sets the value of the bidprice property.
     * 
     */
    public void setBidprice(double value) {
        this.bidprice = value;
    }

    /**
     * Gets the value of the bidsize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBidsize() {
        return bidsize;
    }

    /**
     * Sets the value of the bidsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBidsize(String value) {
        this.bidsize = value;
    }

    /**
     * Gets the value of the change property.
     * 
     */
    public double getChange() {
        return change;
    }

    /**
     * Sets the value of the change property.
     * 
     */
    public void setChange(double value) {
        this.change = value;
    }

    /**
     * Gets the value of the contracthigh property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getContracthigh() {
        return contracthigh;
    }

    /**
     * Sets the value of the contracthigh property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setContracthigh(Object value) {
        this.contracthigh = value;
    }

    /**
     * Gets the value of the contractlow property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getContractlow() {
        return contractlow;
    }

    /**
     * Sets the value of the contractlow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setContractlow(Object value) {
        this.contractlow = value;
    }

    /**
     * Gets the value of the contractsize property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getContractsize() {
        return contractsize;
    }

    /**
     * Sets the value of the contractsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setContractsize(Object value) {
        this.contractsize = value;
    }

    /**
     * Gets the value of the delta property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDelta() {
        return delta;
    }

    /**
     * Sets the value of the delta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDelta(Object value) {
        this.delta = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the dividendamount property.
     * 
     */
    public int getDividendamount() {
        return dividendamount;
    }

    /**
     * Sets the value of the dividendamount property.
     * 
     */
    public void setDividendamount(int value) {
        this.dividendamount = value;
    }

    /**
     * Gets the value of the dividendexdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDividendexdate() {
        return dividendexdate;
    }

    /**
     * Sets the value of the dividendexdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDividendexdate(XMLGregorianCalendar value) {
        this.dividendexdate = value;
    }

    /**
     * Gets the value of the dividendpaydate property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDividendpaydate() {
        return dividendpaydate;
    }

    /**
     * Sets the value of the dividendpaydate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDividendpaydate(Object value) {
        this.dividendpaydate = value;
    }

    /**
     * Gets the value of the dividendyield property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDividendyield() {
        return dividendyield;
    }

    /**
     * Sets the value of the dividendyield property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDividendyield(String value) {
        this.dividendyield = value;
    }

    /**
     * Gets the value of the earningspershare property.
     * 
     */
    public double getEarningspershare() {
        return earningspershare;
    }

    /**
     * Sets the value of the earningspershare property.
     * 
     */
    public void setEarningspershare(double value) {
        this.earningspershare = value;
    }

    /**
     * Gets the value of the exch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExch() {
        return exch;
    }

    /**
     * Sets the value of the exch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExch(String value) {
        this.exch = value;
    }

    /**
     * Gets the value of the expiry property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getExpiry() {
        return expiry;
    }

    /**
     * Sets the value of the expiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setExpiry(Object value) {
        this.expiry = value;
    }

    /**
     * Gets the value of the gamma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGamma() {
        return gamma;
    }

    /**
     * Sets the value of the gamma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGamma(Object value) {
        this.gamma = value;
    }

    /**
     * Gets the value of the high52Price property.
     * 
     */
    public double getHigh52Price() {
        return high52Price;
    }

    /**
     * Sets the value of the high52Price property.
     * 
     */
    public void setHigh52Price(double value) {
        this.high52Price = value;
    }

    /**
     * Gets the value of the highprice property.
     * 
     */
    public double getHighprice() {
        return highprice;
    }

    /**
     * Sets the value of the highprice property.
     * 
     */
    public void setHighprice(double value) {
        this.highprice = value;
    }

    /**
     * Gets the value of the impvolatility property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getImpvolatility() {
        return impvolatility;
    }

    /**
     * Sets the value of the impvolatility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setImpvolatility(Object value) {
        this.impvolatility = value;
    }

    /**
     * Gets the value of the lastclosingprice property.
     * 
     */
    public double getLastclosingprice() {
        return lastclosingprice;
    }

    /**
     * Sets the value of the lastclosingprice property.
     * 
     */
    public void setLastclosingprice(double value) {
        this.lastclosingprice = value;
    }

    /**
     * Gets the value of the lastprice property.
     * 
     */
    public double getLastprice() {
        return lastprice;
    }

    /**
     * Sets the value of the lastprice property.
     * 
     */
    public void setLastprice(double value) {
        this.lastprice = value;
    }

    /**
     * Gets the value of the low52Price property.
     * 
     */
    public double getLow52Price() {
        return low52Price;
    }

    /**
     * Sets the value of the low52Price property.
     * 
     */
    public void setLow52Price(double value) {
        this.low52Price = value;
    }

    /**
     * Gets the value of the lowprice property.
     * 
     */
    public double getLowprice() {
        return lowprice;
    }

    /**
     * Sets the value of the lowprice property.
     * 
     */
    public void setLowprice(double value) {
        this.lowprice = value;
    }

    /**
     * Gets the value of the nav property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNav() {
        return nav;
    }

    /**
     * Sets the value of the nav property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNav(Object value) {
        this.nav = value;
    }

    /**
     * Gets the value of the openinterest property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getOpeninterest() {
        return openinterest;
    }

    /**
     * Sets the value of the openinterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setOpeninterest(Object value) {
        this.openinterest = value;
    }

    /**
     * Gets the value of the openprice property.
     * 
     */
    public double getOpenprice() {
        return openprice;
    }

    /**
     * Sets the value of the openprice property.
     * 
     */
    public void setOpenprice(double value) {
        this.openprice = value;
    }

    /**
     * Gets the value of the optval property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getOptval() {
        return optval;
    }

    /**
     * Sets the value of the optval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setOptval(Object value) {
        this.optval = value;
    }

    /**
     * Gets the value of the optiontype property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getOptiontype() {
        return optiontype;
    }

    /**
     * Sets the value of the optiontype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setOptiontype(Object value) {
        this.optiontype = value;
    }

    /**
     * Gets the value of the pctchange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPctchange() {
        return pctchange;
    }

    /**
     * Sets the value of the pctchange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPctchange(String value) {
        this.pctchange = value;
    }

    /**
     * Gets the value of the priceearningsratio property.
     * 
     */
    public int getPriceearningsratio() {
        return priceearningsratio;
    }

    /**
     * Sets the value of the priceearningsratio property.
     * 
     */
    public void setPriceearningsratio(int value) {
        this.priceearningsratio = value;
    }

    /**
     * Gets the value of the rho property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRho() {
        return rho;
    }

    /**
     * Sets the value of the rho property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRho(Object value) {
        this.rho = value;
    }

    /**
     * Gets the value of the sessionvolume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionvolume() {
        return sessionvolume;
    }

    /**
     * Sets the value of the sessionvolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionvolume(String value) {
        this.sessionvolume = value;
    }

    /**
     * Gets the value of the strike property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStrike() {
        return strike;
    }

    /**
     * Sets the value of the strike property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStrike(Object value) {
        this.strike = value;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

    /**
     * Gets the value of the theta property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTheta() {
        return theta;
    }

    /**
     * Sets the value of the theta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTheta(Object value) {
        this.theta = value;
    }

    /**
     * Gets the value of the unknownsymbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnknownsymbol() {
        return unknownsymbol;
    }

    /**
     * Sets the value of the unknownsymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnknownsymbol(String value) {
        this.unknownsymbol = value;
    }

    /**
     * Gets the value of the vega property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getVega() {
        return vega;
    }

    /**
     * Sets the value of the vega property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setVega(Object value) {
        this.vega = value;
    }

    /**
     * Gets the value of the volatility property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getVolatility() {
        return volatility;
    }

    /**
     * Sets the value of the volatility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setVolatility(Object value) {
        this.volatility = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolume(String value) {
        this.volume = value;
    }

}
