//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.14 at 01:02:12 PM PDT 
//


package com.celexus.conniption.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="asksize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="bidsize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dividenddata">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="amt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="exdate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="paydate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="yield" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="earningspershare" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="high52price" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="highprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="low52price" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="lowprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="openprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="prevclose" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="priceearningsratio" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="sessionvolume" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "asksize",
    "bidsize",
    "dividenddata",
    "earningspershare",
    "high52Price",
    "highprice",
    "low52Price",
    "lowprice",
    "openprice",
    "prevclose",
    "priceearningsratio",
    "sessionvolume",
    "volume"
})
public class Extendedquote {

    protected int asksize;
    protected int bidsize;
    @XmlElement(required = true)
    protected Dividenddata dividenddata;
    protected double earningspershare;
    @XmlElement(name = "high52price")
    protected double high52Price;
    protected double highprice;
    @XmlElement(name = "low52price")
    protected double low52Price;
    protected double lowprice;
    protected double openprice;
    protected double prevclose;
    protected int priceearningsratio;
    protected int sessionvolume;
    protected int volume;

    /**
     * Gets the value of the asksize property.
     * 
     */
    public int getAsksize() {
        return asksize;
    }

    /**
     * Sets the value of the asksize property.
     * 
     */
    public void setAsksize(int value) {
        this.asksize = value;
    }

    /**
     * Gets the value of the bidsize property.
     * 
     */
    public int getBidsize() {
        return bidsize;
    }

    /**
     * Sets the value of the bidsize property.
     * 
     */
    public void setBidsize(int value) {
        this.bidsize = value;
    }

    /**
     * Gets the value of the dividenddata property.
     * 
     * @return
     *     possible object is
     *     {@link Dividenddata }
     *     
     */
    public Dividenddata getDividenddata() {
        return dividenddata;
    }

    /**
     * Sets the value of the dividenddata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dividenddata }
     *     
     */
    public void setDividenddata(Dividenddata value) {
        this.dividenddata = value;
    }

    /**
     * Gets the value of the earningspershare property.
     * 
     */
    public double getEarningspershare() {
        return earningspershare;
    }

    /**
     * Sets the value of the earningspershare property.
     * 
     */
    public void setEarningspershare(double value) {
        this.earningspershare = value;
    }

    /**
     * Gets the value of the high52Price property.
     * 
     */
    public double getHigh52Price() {
        return high52Price;
    }

    /**
     * Sets the value of the high52Price property.
     * 
     */
    public void setHigh52Price(double value) {
        this.high52Price = value;
    }

    /**
     * Gets the value of the highprice property.
     * 
     */
    public double getHighprice() {
        return highprice;
    }

    /**
     * Sets the value of the highprice property.
     * 
     */
    public void setHighprice(double value) {
        this.highprice = value;
    }

    /**
     * Gets the value of the low52Price property.
     * 
     */
    public double getLow52Price() {
        return low52Price;
    }

    /**
     * Sets the value of the low52Price property.
     * 
     */
    public void setLow52Price(double value) {
        this.low52Price = value;
    }

    /**
     * Gets the value of the lowprice property.
     * 
     */
    public double getLowprice() {
        return lowprice;
    }

    /**
     * Sets the value of the lowprice property.
     * 
     */
    public void setLowprice(double value) {
        this.lowprice = value;
    }

    /**
     * Gets the value of the openprice property.
     * 
     */
    public double getOpenprice() {
        return openprice;
    }

    /**
     * Sets the value of the openprice property.
     * 
     */
    public void setOpenprice(double value) {
        this.openprice = value;
    }

    /**
     * Gets the value of the prevclose property.
     * 
     */
    public double getPrevclose() {
        return prevclose;
    }

    /**
     * Sets the value of the prevclose property.
     * 
     */
    public void setPrevclose(double value) {
        this.prevclose = value;
    }

    /**
     * Gets the value of the priceearningsratio property.
     * 
     */
    public int getPriceearningsratio() {
        return priceearningsratio;
    }

    /**
     * Sets the value of the priceearningsratio property.
     * 
     */
    public void setPriceearningsratio(int value) {
        this.priceearningsratio = value;
    }

    /**
     * Gets the value of the sessionvolume property.
     * 
     */
    public int getSessionvolume() {
        return sessionvolume;
    }

    /**
     * Sets the value of the sessionvolume property.
     * 
     */
    public void setSessionvolume(int value) {
        this.sessionvolume = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     */
    public int getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     */
    public void setVolume(int value) {
        this.volume = value;
    }

}
