//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.12 at 04:50:01 PM PDT 
//


package com.celexus.conniption.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accounttype" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="costbasis" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="displaydata">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="accounttype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="assetclass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="costbasis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lastprice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="marketvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="marketvaluechange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="qty" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="gainloss" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="instrument">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cusip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="factor" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="sectyp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="sym" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="marketvalue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="marketvaluechange" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="purchaseprice" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="qty" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="quote">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="lastprice" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="underlying" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accounttype",
    "costbasis",
    "displaydata",
    "gainloss",
    "instrument",
    "marketvalue",
    "marketvaluechange",
    "price",
    "purchaseprice",
    "qty",
    "quote",
    "underlying"
})
public class Holding {

    protected byte accounttype;
    protected float costbasis;
    @XmlElement(required = true)
    protected Displaydata displaydata;
    protected float gainloss;
    @XmlElement(required = true)
    protected Instrument instrument;
    protected float marketvalue;
    protected float marketvaluechange;
    protected float price;
    protected float purchaseprice;
    protected float qty;
    @XmlElement(required = true)
    protected Quote quote;
    @XmlElement(required = true)
    protected String underlying;

    /**
     * Gets the value of the accounttype property.
     * 
     */
    public byte getAccounttype() {
        return accounttype;
    }

    /**
     * Sets the value of the accounttype property.
     * 
     */
    public void setAccounttype(byte value) {
        this.accounttype = value;
    }

    /**
     * Gets the value of the costbasis property.
     * 
     */
    public float getCostbasis() {
        return costbasis;
    }

    /**
     * Sets the value of the costbasis property.
     * 
     */
    public void setCostbasis(float value) {
        this.costbasis = value;
    }

    /**
     * Gets the value of the displaydata property.
     * 
     * @return
     *     possible object is
     *     {@link Displaydata }
     *     
     */
    public Displaydata getDisplaydata() {
        return displaydata;
    }

    /**
     * Sets the value of the displaydata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Displaydata }
     *     
     */
    public void setDisplaydata(Displaydata value) {
        this.displaydata = value;
    }

    /**
     * Gets the value of the gainloss property.
     * 
     */
    public float getGainloss() {
        return gainloss;
    }

    /**
     * Sets the value of the gainloss property.
     * 
     */
    public void setGainloss(float value) {
        this.gainloss = value;
    }

    /**
     * Gets the value of the instrument property.
     * 
     * @return
     *     possible object is
     *     {@link Instrument }
     *     
     */
    public Instrument getInstrument() {
        return instrument;
    }

    /**
     * Sets the value of the instrument property.
     * 
     * @param value
     *     allowed object is
     *     {@link Instrument }
     *     
     */
    public void setInstrument(Instrument value) {
        this.instrument = value;
    }

    /**
     * Gets the value of the marketvalue property.
     * 
     */
    public float getMarketvalue() {
        return marketvalue;
    }

    /**
     * Sets the value of the marketvalue property.
     * 
     */
    public void setMarketvalue(float value) {
        this.marketvalue = value;
    }

    /**
     * Gets the value of the marketvaluechange property.
     * 
     */
    public float getMarketvaluechange() {
        return marketvaluechange;
    }

    /**
     * Sets the value of the marketvaluechange property.
     * 
     */
    public void setMarketvaluechange(float value) {
        this.marketvaluechange = value;
    }

    /**
     * Gets the value of the price property.
     * 
     */
    public float getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     */
    public void setPrice(float value) {
        this.price = value;
    }

    /**
     * Gets the value of the purchaseprice property.
     * 
     */
    public float getPurchaseprice() {
        return purchaseprice;
    }

    /**
     * Sets the value of the purchaseprice property.
     * 
     */
    public void setPurchaseprice(float value) {
        this.purchaseprice = value;
    }

    /**
     * Gets the value of the qty property.
     * 
     */
    public float getQty() {
        return qty;
    }

    /**
     * Sets the value of the qty property.
     * 
     */
    public void setQty(float value) {
        this.qty = value;
    }

    /**
     * Gets the value of the quote property.
     * 
     * @return
     *     possible object is
     *     {@link Quote }
     *     
     */
    public Quote getQuote() {
        return quote;
    }

    /**
     * Sets the value of the quote property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quote }
     *     
     */
    public void setQuote(Quote value) {
        this.quote = value;
    }

    /**
     * Gets the value of the underlying property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnderlying() {
        return underlying;
    }

    /**
     * Sets the value of the underlying property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnderlying(String value) {
        this.underlying = value;
    }

}
