//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.12 at 04:50:01 PM PDT 
//


package com.celexus.conniption.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.celexus.conniption.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.celexus.conniption.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Accounts }
     * 
     */
    public Accounts createAccounts() {
        return new Accounts();
    }

    /**
     * Create an instance of {@link Accountsummary }
     * 
     */
    public Accountsummary createAccountsummary() {
        return new Accountsummary();
    }

    /**
     * Create an instance of {@link Accountbalance }
     * 
     */
    public Accountbalance createAccountbalance() {
        return new Accountbalance();
    }

    /**
     * Create an instance of {@link Accountholdings }
     * 
     */
    public Accountholdings createAccountholdings() {
        return new Accountholdings();
    }

    /**
     * Create an instance of {@link Holding }
     * 
     */
    public Holding createHolding() {
        return new Holding();
    }

    /**
     * Create an instance of {@link Displaydata }
     * 
     */
    public Displaydata createDisplaydata() {
        return new Displaydata();
    }

    /**
     * Create an instance of {@link Instrument }
     * 
     */
    public Instrument createInstrument() {
        return new Instrument();
    }

    /**
     * Create an instance of {@link Buyingpower }
     * 
     */
    public Buyingpower createBuyingpower() {
        return new Buyingpower();
    }

    /**
     * Create an instance of {@link Money }
     * 
     */
    public Money createMoney() {
        return new Money();
    }

    /**
     * Create an instance of {@link Securities }
     * 
     */
    public Securities createSecurities() {
        return new Securities();
    }

    /**
     * Create an instance of {@link Quotes }
     * 
     */
    public Quotes createQuotes() {
        return new Quotes();
    }

    /**
     * Create an instance of {@link Quote }
     * 
     */
    public Quote createQuote() {
        return new Quote();
    }

    /**
     * Create an instance of {@link Clock }
     * 
     */
    public Clock createClock() {
        return new Clock();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link OrderQuotes }
     * 
     */
    public OrderQuotes createOrderQuotes() {
        return new OrderQuotes();
    }

    /**
     * Create an instance of {@link OrderQuote }
     * 
     */
    public OrderQuote createOrderQuote() {
        return new OrderQuote();
    }

}
