//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.14 at 02:43:01 PM PDT 
//


package com.celexus.conniption.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="warning">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="warningcode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="warningtext" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="estcommission" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="marginrequirement" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="netamt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="principal" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="quotes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="instrumentquote">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="displaydata">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="accounttype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="assetclass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="costbasis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="marketvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="marketvaluechange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="qty" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="askprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="asksize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="bidprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="bidsize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="contracthigh" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="contractlow" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="contractsize" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="delta" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="dividendamount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="dividendexdate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                                       &lt;element name="dividendpaydate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="dividendyield" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="earningspershare" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="exch" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="expiry" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="gamma" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="high52price" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="highprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="impvolatility" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="lastclosingprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="lastprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="low52price" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="lowprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="nav" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="openinterest" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="openprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="optval" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="optiontype" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="pctchange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="priceearningsratio" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="rho" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="sessionvolume" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="strike" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="theta" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="unknownsymbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="vega" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="volatility" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="greeks" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="instrument">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="exch" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="sectyp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="sym" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="quote">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="askprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="bidprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="extendedquote">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="asksize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="bidsize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="dividenddata">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="amt" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                                           &lt;element name="exdate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                                           &lt;element name="paydate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                                           &lt;element name="yield" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                                 &lt;element name="earningspershare" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                                 &lt;element name="high52price" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                                 &lt;element name="highprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                                 &lt;element name="low52price" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                                 &lt;element name="lowprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                                 &lt;element name="openprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                                 &lt;element name="prevclose" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                                 &lt;element name="priceearningsratio" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="sessionvolume" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="lastprice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="pctchange" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="unknownsymbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="secfee" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "elapsedtime",
    "warning",
    "estcommission",
    "marginrequirement",
    "netamt",
    "principal",
    "quotes",
    "secfee",
    "error"
})
@XmlRootElement(name = "response")
public class Order {

    @XmlElement(required = true)
    protected Warning warning;
    protected double estcommission;
    protected int marginrequirement;
    protected double netamt;
    protected double principal;
    @XmlElement(required = true)
    protected OrderQuotes quotes;
    protected int secfee;
    @XmlAttribute(name = "id")
    protected String id;
    protected int elapsedtime;
    protected String error;
    /**
     * Gets the value of the elapsedtime property.
     * 
     */
    public int getElapsedtime() {
        return elapsedtime;
    }

    /**
     * Sets the value of the elapsedtime property.
     * 
     */
    public void setElapsedtime(int value) {
        this.elapsedtime = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setError(String value) {
        this.error = value;
    }

    /**
     * Gets the value of the warning property.
     * 
     * @return
     *     possible object is
     *     {@link Warning }
     *     
     */
    public Warning getWarning() {
        return warning;
    }

    /**
     * Sets the value of the warning property.
     * 
     * @param value
     *     allowed object is
     *     {@link Warning }
     *     
     */
    public void setWarning(Warning value) {
        this.warning = value;
    }

    /**
     * Gets the value of the estcommission property.
     * 
     */
    public double getEstcommission() {
        return estcommission;
    }

    /**
     * Sets the value of the estcommission property.
     * 
     */
    public void setEstcommission(double value) {
        this.estcommission = value;
    }

    /**
     * Gets the value of the marginrequirement property.
     * 
     */
    public int getMarginrequirement() {
        return marginrequirement;
    }

    /**
     * Sets the value of the marginrequirement property.
     * 
     */
    public void setMarginrequirement(int value) {
        this.marginrequirement = value;
    }

    /**
     * Gets the value of the netamt property.
     * 
     */
    public double getNetamt() {
        return netamt;
    }

    /**
     * Sets the value of the netamt property.
     * 
     */
    public void setNetamt(double value) {
        this.netamt = value;
    }

    /**
     * Gets the value of the principal property.
     * 
     */
    public double getPrincipal() {
        return principal;
    }

    /**
     * Sets the value of the principal property.
     * 
     */
    public void setPrincipal(double value) {
        this.principal = value;
    }

    /**
     * Gets the value of the quotes property.
     * 
     * @return
     *     possible object is
     *     {@link OrderQuotes }
     *     
     */
    public OrderQuotes getQuotes() {
        return quotes;
    }

    /**
     * Sets the value of the quotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderQuotes }
     *     
     */
    public void setQuotes(OrderQuotes value) {
        this.quotes = value;
    }

    /**
     * Gets the value of the secfee property.
     * 
     */
    public int getSecfee() {
        return secfee;
    }

    /**
     * Sets the value of the secfee property.
     * 
     */
    public void setSecfee(int value) {
        this.secfee = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
