//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.14 at 11:34:34 AM PDT 
//


package com.celexus.conniption.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="adp_100" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="adp_200" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="adp_50" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="adv_21" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="adv_30" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="adv_90" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ask" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ask_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="asksz" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="basis" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="beta" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="bid" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="bid_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bidsz" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="bidtick" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="chg" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="chg_sign" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="chg_t" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="cl" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="cusip" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="datetime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="div" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="divexdate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="divpaydt" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dollar_value" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="eps" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="exch" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="exch_desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hi" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="iad" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="incr_vl" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="last" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="lo" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="op_flag" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="opn" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="pchg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pchg_sign" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pcls" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="pe" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="phi" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="plo" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="popn" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="pr_adp_100" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="pr_adp_200" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="pr_adp_50" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="pr_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="prbook" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="prchg" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="pvol" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="secclass" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="sesn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sho" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="symbol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tcond" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="tr_num" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="tradetick" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="trend" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vl" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="volatility12" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="vwap" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="wk52hi" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="wk52hidate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="wk52lo" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="wk52lodate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="change" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="lastprice" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "adp100",
    "adp200",
    "adp50",
    "adv21",
    "adv30",
    "adv90",
    "ask",
    "askTime",
    "asksz",
    "basis",
    "beta",
    "bid",
    "bidTime",
    "bidsz",
    "bidtick",
    "chg",
    "chgSign",
    "chgT",
    "cl",
    "cusip",
    "date",
    "datetime",
    "div",
    "divexdate",
    "divpaydt",
    "dollarValue",
    "eps",
    "exch",
    "exchDesc",
    "hi",
    "iad",
    "incrVl",
    "last",
    "lo",
    "name",
    "opFlag",
    "opn",
    "pchg",
    "pchgSign",
    "pcls",
    "pe",
    "phi",
    "plo",
    "popn",
    "prAdp100",
    "prAdp200",
    "prAdp50",
    "prDate",
    "prbook",
    "prchg",
    "pvol",
    "secclass",
    "sesn",
    "sho",
    "symbol",
    "tcond",
    "timestamp",
    "trNum",
    "tradetick",
    "trend",
    "vl",
    "volatility12",
    "vwap",
    "wk52Hi",
    "wk52Hidate",
    "wk52Lo",
    "wk52Lodate",
    "change",
    "lastprice"
})
public class Quote {

    @XmlElement(name = "adp_100")
    protected double adp100;
    @XmlElement(name = "adp_200")
    protected double adp200;
    @XmlElement(name = "adp_50")
    protected double adp50;
    @XmlElement(name = "adv_21")
    protected int adv21;
    @XmlElement(name = "adv_30")
    protected int adv30;
    @XmlElement(name = "adv_90")
    protected int adv90;
    protected double ask;
    @XmlElement(name = "ask_time", required = true)
    protected String askTime;
    protected int asksz;
    protected int basis;
    protected double beta;
    protected double bid;
    @XmlElement(name = "bid_time", required = true)
    protected String bidTime;
    protected int bidsz;
    protected int bidtick;
    protected double chg;
    @XmlElement(name = "chg_sign", required = true)
    protected String chgSign;
    @XmlElement(name = "chg_t")
    protected double chgT;
    protected double cl;
    protected int cusip;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datetime;
    protected double div;
    protected int divexdate;
    protected int divpaydt;
    @XmlElement(name = "dollar_value")
    protected int dollarValue;
    protected double eps;
    @XmlElement(required = true)
    protected String exch;
    @XmlElement(name = "exch_desc", required = true)
    protected String exchDesc;
    protected double hi;
    protected int iad;
    @XmlElement(name = "incr_vl")
    protected int incrVl;
    protected double last;
    protected double lo;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "op_flag")
    protected int opFlag;
    protected double opn;
    @XmlElement(required = true)
    protected String pchg;
    @XmlElement(name = "pchg_sign", required = true)
    protected String pchgSign;
    protected double pcls;
    protected double pe;
    protected double phi;
    protected double plo;
    protected double popn;
    @XmlElement(name = "pr_adp_100")
    protected double prAdp100;
    @XmlElement(name = "pr_adp_200")
    protected double prAdp200;
    @XmlElement(name = "pr_adp_50")
    protected double prAdp50;
    @XmlElement(name = "pr_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar prDate;
    protected double prbook;
    protected double prchg;
    protected int pvol;
    protected int secclass;
    @XmlElement(required = true)
    protected String sesn;
    @XmlElement(required = true)
    protected String sho;
    @XmlElement(required = true)
    protected String symbol;
    @XmlElement(required = true)
    protected String tcond;
    protected int timestamp;
    @XmlElement(name = "tr_num")
    protected int trNum;
    @XmlElement(required = true)
    protected String tradetick;
    @XmlElement(required = true)
    protected String trend;
    protected int vl;
    protected double volatility12;
    protected double vwap;
    @XmlElement(name = "wk52hi")
    protected double wk52Hi;
    @XmlElement(name = "wk52hidate")
    protected int wk52Hidate;
    @XmlElement(name = "wk52lo")
    protected double wk52Lo;
    @XmlElement(name = "wk52lodate")
    protected int wk52Lodate;
    protected float change;
    protected float lastprice;

    /**
     * Gets the value of the adp100 property.
     * 
     */
    public double getAdp100() {
        return adp100;
    }

    /**
     * Sets the value of the adp100 property.
     * 
     */
    public void setAdp100(double value) {
        this.adp100 = value;
    }

    /**
     * Gets the value of the adp200 property.
     * 
     */
    public double getAdp200() {
        return adp200;
    }

    /**
     * Sets the value of the adp200 property.
     * 
     */
    public void setAdp200(double value) {
        this.adp200 = value;
    }

    /**
     * Gets the value of the adp50 property.
     * 
     */
    public double getAdp50() {
        return adp50;
    }

    /**
     * Sets the value of the adp50 property.
     * 
     */
    public void setAdp50(double value) {
        this.adp50 = value;
    }

    /**
     * Gets the value of the adv21 property.
     * 
     */
    public int getAdv21() {
        return adv21;
    }

    /**
     * Sets the value of the adv21 property.
     * 
     */
    public void setAdv21(int value) {
        this.adv21 = value;
    }

    /**
     * Gets the value of the adv30 property.
     * 
     */
    public int getAdv30() {
        return adv30;
    }

    /**
     * Sets the value of the adv30 property.
     * 
     */
    public void setAdv30(int value) {
        this.adv30 = value;
    }

    /**
     * Gets the value of the adv90 property.
     * 
     */
    public int getAdv90() {
        return adv90;
    }

    /**
     * Sets the value of the adv90 property.
     * 
     */
    public void setAdv90(int value) {
        this.adv90 = value;
    }

    /**
     * Gets the value of the ask property.
     * 
     */
    public double getAsk() {
        return ask;
    }

    /**
     * Sets the value of the ask property.
     * 
     */
    public void setAsk(double value) {
        this.ask = value;
    }

    /**
     * Gets the value of the askTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAskTime() {
        return askTime;
    }

    /**
     * Sets the value of the askTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAskTime(String value) {
        this.askTime = value;
    }

    /**
     * Gets the value of the asksz property.
     * 
     */
    public int getAsksz() {
        return asksz;
    }

    /**
     * Sets the value of the asksz property.
     * 
     */
    public void setAsksz(int value) {
        this.asksz = value;
    }

    /**
     * Gets the value of the basis property.
     * 
     */
    public int getBasis() {
        return basis;
    }

    /**
     * Sets the value of the basis property.
     * 
     */
    public void setBasis(int value) {
        this.basis = value;
    }

    /**
     * Gets the value of the beta property.
     * 
     */
    public double getBeta() {
        return beta;
    }

    /**
     * Sets the value of the beta property.
     * 
     */
    public void setBeta(double value) {
        this.beta = value;
    }

    /**
     * Gets the value of the bid property.
     * 
     */
    public double getBid() {
        return bid;
    }

    /**
     * Sets the value of the bid property.
     * 
     */
    public void setBid(double value) {
        this.bid = value;
    }

    /**
     * Gets the value of the bidTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBidTime() {
        return bidTime;
    }

    /**
     * Sets the value of the bidTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBidTime(String value) {
        this.bidTime = value;
    }

    /**
     * Gets the value of the bidsz property.
     * 
     */
    public int getBidsz() {
        return bidsz;
    }

    /**
     * Sets the value of the bidsz property.
     * 
     */
    public void setBidsz(int value) {
        this.bidsz = value;
    }

    /**
     * Gets the value of the bidtick property.
     * 
     */
    public int getBidtick() {
        return bidtick;
    }

    /**
     * Sets the value of the bidtick property.
     * 
     */
    public void setBidtick(int value) {
        this.bidtick = value;
    }

    /**
     * Gets the value of the chg property.
     * 
     */
    public double getChg() {
        return chg;
    }

    /**
     * Sets the value of the chg property.
     * 
     */
    public void setChg(double value) {
        this.chg = value;
    }

    /**
     * Gets the value of the chgSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChgSign() {
        return chgSign;
    }

    /**
     * Sets the value of the chgSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChgSign(String value) {
        this.chgSign = value;
    }

    /**
     * Gets the value of the chgT property.
     * 
     */
    public double getChgT() {
        return chgT;
    }

    /**
     * Sets the value of the chgT property.
     * 
     */
    public void setChgT(double value) {
        this.chgT = value;
    }

    /**
     * Gets the value of the cl property.
     * 
     */
    public double getCl() {
        return cl;
    }

    /**
     * Sets the value of the cl property.
     * 
     */
    public void setCl(double value) {
        this.cl = value;
    }

    /**
     * Gets the value of the cusip property.
     * 
     */
    public int getCusip() {
        return cusip;
    }

    /**
     * Sets the value of the cusip property.
     * 
     */
    public void setCusip(int value) {
        this.cusip = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the datetime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatetime() {
        return datetime;
    }

    /**
     * Sets the value of the datetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatetime(XMLGregorianCalendar value) {
        this.datetime = value;
    }

    /**
     * Gets the value of the div property.
     * 
     */
    public double getDiv() {
        return div;
    }

    /**
     * Sets the value of the div property.
     * 
     */
    public void setDiv(double value) {
        this.div = value;
    }

    /**
     * Gets the value of the divexdate property.
     * 
     */
    public int getDivexdate() {
        return divexdate;
    }

    /**
     * Sets the value of the divexdate property.
     * 
     */
    public void setDivexdate(int value) {
        this.divexdate = value;
    }

    /**
     * Gets the value of the divpaydt property.
     * 
     */
    public int getDivpaydt() {
        return divpaydt;
    }

    /**
     * Sets the value of the divpaydt property.
     * 
     */
    public void setDivpaydt(int value) {
        this.divpaydt = value;
    }

    /**
     * Gets the value of the dollarValue property.
     * 
     */
    public int getDollarValue() {
        return dollarValue;
    }

    /**
     * Sets the value of the dollarValue property.
     * 
     */
    public void setDollarValue(int value) {
        this.dollarValue = value;
    }

    /**
     * Gets the value of the eps property.
     * 
     */
    public double getEps() {
        return eps;
    }

    /**
     * Sets the value of the eps property.
     * 
     */
    public void setEps(double value) {
        this.eps = value;
    }

    /**
     * Gets the value of the exch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExch() {
        return exch;
    }

    /**
     * Sets the value of the exch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExch(String value) {
        this.exch = value;
    }

    /**
     * Gets the value of the exchDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchDesc() {
        return exchDesc;
    }

    /**
     * Sets the value of the exchDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchDesc(String value) {
        this.exchDesc = value;
    }

    /**
     * Gets the value of the hi property.
     * 
     */
    public double getHi() {
        return hi;
    }

    /**
     * Sets the value of the hi property.
     * 
     */
    public void setHi(double value) {
        this.hi = value;
    }

    /**
     * Gets the value of the iad property.
     * 
     */
    public int getIad() {
        return iad;
    }

    /**
     * Sets the value of the iad property.
     * 
     */
    public void setIad(int value) {
        this.iad = value;
    }

    /**
     * Gets the value of the incrVl property.
     * 
     */
    public int getIncrVl() {
        return incrVl;
    }

    /**
     * Sets the value of the incrVl property.
     * 
     */
    public void setIncrVl(int value) {
        this.incrVl = value;
    }

    /**
     * Gets the value of the last property.
     * 
     */
    public double getLast() {
        return last;
    }

    /**
     * Sets the value of the last property.
     * 
     */
    public void setLast(double value) {
        this.last = value;
    }

    /**
     * Gets the value of the lo property.
     * 
     */
    public double getLo() {
        return lo;
    }

    /**
     * Sets the value of the lo property.
     * 
     */
    public void setLo(double value) {
        this.lo = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the opFlag property.
     * 
     */
    public int getOpFlag() {
        return opFlag;
    }

    /**
     * Sets the value of the opFlag property.
     * 
     */
    public void setOpFlag(int value) {
        this.opFlag = value;
    }

    /**
     * Gets the value of the opn property.
     * 
     */
    public double getOpn() {
        return opn;
    }

    /**
     * Sets the value of the opn property.
     * 
     */
    public void setOpn(double value) {
        this.opn = value;
    }

    /**
     * Gets the value of the pchg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPchg() {
        return pchg;
    }

    /**
     * Sets the value of the pchg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPchg(String value) {
        this.pchg = value;
    }

    /**
     * Gets the value of the pchgSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPchgSign() {
        return pchgSign;
    }

    /**
     * Sets the value of the pchgSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPchgSign(String value) {
        this.pchgSign = value;
    }

    /**
     * Gets the value of the pcls property.
     * 
     */
    public double getPcls() {
        return pcls;
    }

    /**
     * Sets the value of the pcls property.
     * 
     */
    public void setPcls(double value) {
        this.pcls = value;
    }

    /**
     * Gets the value of the pe property.
     * 
     */
    public double getPe() {
        return pe;
    }

    /**
     * Sets the value of the pe property.
     * 
     */
    public void setPe(double value) {
        this.pe = value;
    }

    /**
     * Gets the value of the phi property.
     * 
     */
    public double getPhi() {
        return phi;
    }

    /**
     * Sets the value of the phi property.
     * 
     */
    public void setPhi(double value) {
        this.phi = value;
    }

    /**
     * Gets the value of the plo property.
     * 
     */
    public double getPlo() {
        return plo;
    }

    /**
     * Sets the value of the plo property.
     * 
     */
    public void setPlo(double value) {
        this.plo = value;
    }

    /**
     * Gets the value of the popn property.
     * 
     */
    public double getPopn() {
        return popn;
    }

    /**
     * Sets the value of the popn property.
     * 
     */
    public void setPopn(double value) {
        this.popn = value;
    }

    /**
     * Gets the value of the prAdp100 property.
     * 
     */
    public double getPrAdp100() {
        return prAdp100;
    }

    /**
     * Sets the value of the prAdp100 property.
     * 
     */
    public void setPrAdp100(double value) {
        this.prAdp100 = value;
    }

    /**
     * Gets the value of the prAdp200 property.
     * 
     */
    public double getPrAdp200() {
        return prAdp200;
    }

    /**
     * Sets the value of the prAdp200 property.
     * 
     */
    public void setPrAdp200(double value) {
        this.prAdp200 = value;
    }

    /**
     * Gets the value of the prAdp50 property.
     * 
     */
    public double getPrAdp50() {
        return prAdp50;
    }

    /**
     * Sets the value of the prAdp50 property.
     * 
     */
    public void setPrAdp50(double value) {
        this.prAdp50 = value;
    }

    /**
     * Gets the value of the prDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPrDate() {
        return prDate;
    }

    /**
     * Sets the value of the prDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPrDate(XMLGregorianCalendar value) {
        this.prDate = value;
    }

    /**
     * Gets the value of the prbook property.
     * 
     */
    public double getPrbook() {
        return prbook;
    }

    /**
     * Sets the value of the prbook property.
     * 
     */
    public void setPrbook(double value) {
        this.prbook = value;
    }

    /**
     * Gets the value of the prchg property.
     * 
     */
    public double getPrchg() {
        return prchg;
    }

    /**
     * Sets the value of the prchg property.
     * 
     */
    public void setPrchg(double value) {
        this.prchg = value;
    }

    /**
     * Gets the value of the pvol property.
     * 
     */
    public int getPvol() {
        return pvol;
    }

    /**
     * Sets the value of the pvol property.
     * 
     */
    public void setPvol(int value) {
        this.pvol = value;
    }

    /**
     * Gets the value of the secclass property.
     * 
     */
    public int getSecclass() {
        return secclass;
    }

    /**
     * Sets the value of the secclass property.
     * 
     */
    public void setSecclass(int value) {
        this.secclass = value;
    }

    /**
     * Gets the value of the sesn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSesn() {
        return sesn;
    }

    /**
     * Sets the value of the sesn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSesn(String value) {
        this.sesn = value;
    }

    /**
     * Gets the value of the sho property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSho() {
        return sho;
    }

    /**
     * Sets the value of the sho property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSho(String value) {
        this.sho = value;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

    /**
     * Gets the value of the tcond property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTcond() {
        return tcond;
    }

    /**
     * Sets the value of the tcond property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTcond(String value) {
        this.tcond = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     */
    public int getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     */
    public void setTimestamp(int value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the trNum property.
     * 
     */
    public int getTrNum() {
        return trNum;
    }

    /**
     * Sets the value of the trNum property.
     * 
     */
    public void setTrNum(int value) {
        this.trNum = value;
    }

    /**
     * Gets the value of the tradetick property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradetick() {
        return tradetick;
    }

    /**
     * Sets the value of the tradetick property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradetick(String value) {
        this.tradetick = value;
    }

    /**
     * Gets the value of the trend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrend() {
        return trend;
    }

    /**
     * Sets the value of the trend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrend(String value) {
        this.trend = value;
    }

    /**
     * Gets the value of the vl property.
     * 
     */
    public int getVl() {
        return vl;
    }

    /**
     * Sets the value of the vl property.
     * 
     */
    public void setVl(int value) {
        this.vl = value;
    }

    /**
     * Gets the value of the volatility12 property.
     * 
     */
    public double getVolatility12() {
        return volatility12;
    }

    /**
     * Sets the value of the volatility12 property.
     * 
     */
    public void setVolatility12(double value) {
        this.volatility12 = value;
    }

    /**
     * Gets the value of the vwap property.
     * 
     */
    public double getVwap() {
        return vwap;
    }

    /**
     * Sets the value of the vwap property.
     * 
     */
    public void setVwap(double value) {
        this.vwap = value;
    }

    /**
     * Gets the value of the wk52Hi property.
     * 
     */
    public double getWk52Hi() {
        return wk52Hi;
    }

    /**
     * Sets the value of the wk52Hi property.
     * 
     */
    public void setWk52Hi(double value) {
        this.wk52Hi = value;
    }

    /**
     * Gets the value of the wk52Hidate property.
     * 
     */
    public int getWk52Hidate() {
        return wk52Hidate;
    }

    /**
     * Sets the value of the wk52Hidate property.
     * 
     */
    public void setWk52Hidate(int value) {
        this.wk52Hidate = value;
    }

    /**
     * Gets the value of the wk52Lo property.
     * 
     */
    public double getWk52Lo() {
        return wk52Lo;
    }

    /**
     * Sets the value of the wk52Lo property.
     * 
     */
    public void setWk52Lo(double value) {
        this.wk52Lo = value;
    }

    /**
     * Gets the value of the wk52Lodate property.
     * 
     */
    public int getWk52Lodate() {
        return wk52Lodate;
    }

    /**
     * Sets the value of the wk52Lodate property.
     * 
     */
    public void setWk52Lodate(int value) {
        this.wk52Lodate = value;
    }

    /**
     * Gets the value of the change property.
     * 
     */
    public float getChange() {
        return change;
    }

    /**
     * Sets the value of the change property.
     * 
     */
    public void setChange(float value) {
        this.change = value;
    }

    /**
     * Gets the value of the lastprice property.
     * 
     */
    public float getLastprice() {
        return lastprice;
    }

    /**
     * Sets the value of the lastprice property.
     * 
     */
    public void setLastprice(float value) {
        this.lastprice = value;
    }

}
