//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.12 at 04:50:01 PM PDT 
//


package com.celexus.conniption.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="account" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="accountvalue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="buyingpower">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cashavailableforwithdrawal" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="daytrading" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="equitypercentage" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="options" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="soddaytrading" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="sodoptions" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="sodstock" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="stock" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fedcall" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="housecall" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="money">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="accruedinterest" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="cash" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="cashavailable" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="marginbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="mmf" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="total" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="uncleareddeposits" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="unsettledfunds" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="yield" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="securities">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="longoptions" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="longstocks" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="options" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="shortoptions" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="shortstocks" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="stocks" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="total" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "account",
    "accountvalue",
    "buyingpower",
    "fedcall",
    "housecall",
    "money",
    "securities"
})
public class Accountbalance {

    protected int account;
    protected float accountvalue;
    @XmlElement(required = true)
    protected Buyingpower buyingpower;
    protected float fedcall;
    protected float housecall;
    @XmlElement(required = true)
    protected Money money;
    @XmlElement(required = true)
    protected Securities securities;

    /**
     * Gets the value of the account property.
     * 
     */
    public int getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     */
    public void setAccount(int value) {
        this.account = value;
    }

    /**
     * Gets the value of the accountvalue property.
     * 
     */
    public float getAccountvalue() {
        return accountvalue;
    }

    /**
     * Sets the value of the accountvalue property.
     * 
     */
    public void setAccountvalue(float value) {
        this.accountvalue = value;
    }

    /**
     * Gets the value of the buyingpower property.
     * 
     * @return
     *     possible object is
     *     {@link Buyingpower }
     *     
     */
    public Buyingpower getBuyingpower() {
        return buyingpower;
    }

    /**
     * Sets the value of the buyingpower property.
     * 
     * @param value
     *     allowed object is
     *     {@link Buyingpower }
     *     
     */
    public void setBuyingpower(Buyingpower value) {
        this.buyingpower = value;
    }

    /**
     * Gets the value of the fedcall property.
     * 
     */
    public float getFedcall() {
        return fedcall;
    }

    /**
     * Sets the value of the fedcall property.
     * 
     */
    public void setFedcall(float value) {
        this.fedcall = value;
    }

    /**
     * Gets the value of the housecall property.
     * 
     */
    public float getHousecall() {
        return housecall;
    }

    /**
     * Sets the value of the housecall property.
     * 
     */
    public void setHousecall(float value) {
        this.housecall = value;
    }

    /**
     * Gets the value of the money property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getMoney() {
        return money;
    }

    /**
     * Sets the value of the money property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setMoney(Money value) {
        this.money = value;
    }

    /**
     * Gets the value of the securities property.
     * 
     * @return
     *     possible object is
     *     {@link Securities }
     *     
     */
    public Securities getSecurities() {
        return securities;
    }

    /**
     * Sets the value of the securities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Securities }
     *     
     */
    public void setSecurities(Securities value) {
        this.securities = value;
    }

}
