//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.12 at 04:50:01 PM PDT 
//


package com.celexus.conniption.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accruedinterest" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="cash" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="cashavailable" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="marginbalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="mmf" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="total" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="uncleareddeposits" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="unsettledfunds" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="yield" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accruedinterest",
    "cash",
    "cashavailable",
    "marginbalance",
    "mmf",
    "total",
    "uncleareddeposits",
    "unsettledfunds",
    "yield"
})
public class Money {

    protected float accruedinterest;
    protected float cash;
    protected float cashavailable;
    protected float marginbalance;
    protected float mmf;
    protected float total;
    protected float uncleareddeposits;
    protected float unsettledfunds;
    protected float yield;

    /**
     * Gets the value of the accruedinterest property.
     * 
     */
    public float getAccruedinterest() {
        return accruedinterest;
    }

    /**
     * Sets the value of the accruedinterest property.
     * 
     */
    public void setAccruedinterest(float value) {
        this.accruedinterest = value;
    }

    /**
     * Gets the value of the cash property.
     * 
     */
    public float getCash() {
        return cash;
    }

    /**
     * Sets the value of the cash property.
     * 
     */
    public void setCash(float value) {
        this.cash = value;
    }

    /**
     * Gets the value of the cashavailable property.
     * 
     */
    public float getCashavailable() {
        return cashavailable;
    }

    /**
     * Sets the value of the cashavailable property.
     * 
     */
    public void setCashavailable(float value) {
        this.cashavailable = value;
    }

    /**
     * Gets the value of the marginbalance property.
     * 
     */
    public float getMarginbalance() {
        return marginbalance;
    }

    /**
     * Sets the value of the marginbalance property.
     * 
     */
    public void setMarginbalance(float value) {
        this.marginbalance = value;
    }

    /**
     * Gets the value of the mmf property.
     * 
     */
    public float getMmf() {
        return mmf;
    }

    /**
     * Sets the value of the mmf property.
     * 
     */
    public void setMmf(float value) {
        this.mmf = value;
    }

    /**
     * Gets the value of the total property.
     * 
     */
    public float getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     */
    public void setTotal(float value) {
        this.total = value;
    }

    /**
     * Gets the value of the uncleareddeposits property.
     * 
     */
    public float getUncleareddeposits() {
        return uncleareddeposits;
    }

    /**
     * Sets the value of the uncleareddeposits property.
     * 
     */
    public void setUncleareddeposits(float value) {
        this.uncleareddeposits = value;
    }

    /**
     * Gets the value of the unsettledfunds property.
     * 
     */
    public float getUnsettledfunds() {
        return unsettledfunds;
    }

    /**
     * Sets the value of the unsettledfunds property.
     * 
     */
    public void setUnsettledfunds(float value) {
        this.unsettledfunds = value;
    }

    /**
     * Gets the value of the yield property.
     * 
     */
    public float getYield() {
        return yield;
    }

    /**
     * Sets the value of the yield property.
     * 
     */
    public void setYield(float value) {
        this.yield = value;
    }

}
