//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.12 at 04:50:01 PM PDT 
//


package com.celexus.conniption.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="longoptions" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="longstocks" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="options" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="shortoptions" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="shortstocks" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="stocks" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="total" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "longoptions",
    "longstocks",
    "options",
    "shortoptions",
    "shortstocks",
    "stocks",
    "total"
})
public class Securities {

    protected float longoptions;
    protected float longstocks;
    protected float options;
    protected float shortoptions;
    protected float shortstocks;
    protected float stocks;
    protected float total;

    /**
     * Gets the value of the longoptions property.
     * 
     */
    public float getLongoptions() {
        return longoptions;
    }

    /**
     * Sets the value of the longoptions property.
     * 
     */
    public void setLongoptions(float value) {
        this.longoptions = value;
    }

    /**
     * Gets the value of the longstocks property.
     * 
     */
    public float getLongstocks() {
        return longstocks;
    }

    /**
     * Sets the value of the longstocks property.
     * 
     */
    public void setLongstocks(float value) {
        this.longstocks = value;
    }

    /**
     * Gets the value of the options property.
     * 
     */
    public float getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     */
    public void setOptions(float value) {
        this.options = value;
    }

    /**
     * Gets the value of the shortoptions property.
     * 
     */
    public float getShortoptions() {
        return shortoptions;
    }

    /**
     * Sets the value of the shortoptions property.
     * 
     */
    public void setShortoptions(float value) {
        this.shortoptions = value;
    }

    /**
     * Gets the value of the shortstocks property.
     * 
     */
    public float getShortstocks() {
        return shortstocks;
    }

    /**
     * Sets the value of the shortstocks property.
     * 
     */
    public void setShortstocks(float value) {
        this.shortstocks = value;
    }

    /**
     * Gets the value of the stocks property.
     * 
     */
    public float getStocks() {
        return stocks;
    }

    /**
     * Sets the value of the stocks property.
     * 
     */
    public void setStocks(float value) {
        this.stocks = value;
    }

    /**
     * Gets the value of the total property.
     * 
     */
    public float getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     */
    public void setTotal(float value) {
        this.total = value;
    }

}
